name = "welcome-my-friend"
license = "MIT"
licenselink = "https://github.com/guemax/welcome-my-friend/blob/master/LICENSE"
description = "A simple Hugo theme for by blog."
min_version = 0.30

[author]
  name = "Max Günther"
  homepage = "https:/guemax.de"
  repo = "https://github.com/guemax/welcome-my-friend"

[original]
  name = "Djordje Atlialp"
  homepage = "https://atlialp.com"
  repo = "https://github.com/rhazdon/hugo-theme-hello-friend-ng"
